### ISSUE TITLE
"Apply attributes to selected features" is always greyed out

### ISSUE THREAD

**Issue by pcav** [enricofer/attributepainter#3]
I think I followed the instructions, but I always have "Apply attributes to selected features" inactive.

**Comment by enricofer** [comment]
I tried the plugin in Windows and Ubuntu and I didn't found any problem.
The behaviour you report happens when the selected layer isn't in editing state.
The plugin, from the last release, make use of EditBuffer and tracks the layers editing state changes for enabling or disabling dynamically the behaviour of the buttons and the attributes table.
Perhaps you installed the plugin without restarting qgis, and changes on loaded layers were not detected and had not reflect on the button.

**Comment by pcav** [comment]
OK, thanks. It was unclear to me that the layer ha to be in editing mode (I may have overlooked in the instructions).

**Comment by enricofer** [comment]
Keep in mind that the new release of attribute painter allow to copy attributes values between different layers. The compatible fields appear black while others are greyed out.
